name: Pantheon YML Editor
on:
  push:
  pull_request:
jobs:
  build_test:
    runs-on: ubuntu-latest
    container:
      image: quay.io/pantheon-public/php-ci:4.x
      options: --user root
    name: Build and test
    env:
      TZ: "/usr/share/zoneinfo/America/Los_Angeles"
      TERM: dumb
      GITHUB_RUN_NUMBER: ${{ github.run_number }}
      COMMIT_SHA: ${{ github.sha }}
      BASH_ENV: ~/.bashrc
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Composer install
        run: composer install

      - name: Code sniff
        run: composer cs

      - name: Run tests
        run: ./tests/run.sh
